### ISSUE TITLE
Server intermittently omits the Access-Control-Allow-Origin header from XHR responses.

### ISSUE THREAD

**Issue by abrinckm** [CenterForOpenScience/ember-osf#154]
Sorry for the lack of useful information on this one. At the moment, the problem seemingly occurs at random when issuing a batch of requests. I'm seeing an error that looks like this:

```
XMLHttpRequest cannot load https://staging-api.osf.io/v2/nodes/<node_id>/. 
No 'Access-Control-Allow-Origin' header is present on the requested resource. 
Origin 'http://localhost:4200' is therefore not allowed access.
```

The only info I have is this:
* At a rough estimate, I'll say that it happens about 1 out of every 10 requests.
* It seems it can happen with any OSF endpoint, but have observed `/v2/nodes/`, node relationship links, and `/v2/users/` 
* It seems? that I'm able to greatly mitigate the problem by throttling requests down to ~1 per second (at the cost of making the user wait for page content).
* I've only tested against host staging-api.osf.io.

**Comment by abrinckm** [comment]
Actually, I'm not sure if this issue should really go here https://github.com/CenterForOpenScience/osf.io

**Comment by abought** [comment]
This does seem to be an API issue, rather than ember-osf, and is best reported in the OSF issue tracker if it persists.

As a general note, the most common reason I find for a CORS header to be missing is that the server responded with an error code (4xx or 5xx). In that case, the lack of CORS headers is simply because the response didn't complete (it stopped before the "add CORS headers" step.) The CORS error message can be a red herring, and is often mitigated by looking at the reason the request failed. You can find this information on the "network" tab in Chrome DevTools. Each failed request should return a payload describing the reason for the error.

The API does implement rate limiting, so I suspect you will find 429 status codes are involved. We are currently evolving our rate limiting feature, and I'll tag API team lead @brianjgeiger on the assumption this is related.

**Comment by brianjgeiger** [comment]
Okay, we're seeing if we can reproduce. If you want to try to help us narrow it down, if you do a request to `/v2/test/throttle/` I think four times within an hour, it will start throttling you. You can see if it presents the failure in the same way or if it gives you a proper throttle error.

**Comment by brianjgeiger** [comment]
We were not able to reproduce it; we always got the proper 429 error. Let us know if you can narrow down the circumstances a bit more.
