### ISSUE TITLE
Look into comments

### ISSUE THREAD

**Issue by samchrisinger** [CenterForOpenScience/ember-osf#95]
Two things to look into:
- The `Node.comments` relationship is not filtering correctly. We may need to double check the that this uses the URL provided in the relationships link on the Node's payload. 
- The `Comment.replies` relationships also is not filtering correctly.

**Comment by abought** [comment]
Interesting. Can you clarify what is meant by "filtering"?

**Comment by Macainian** [comment]
It isn't using query strings to tell it to only return top level comments. By default it is sending back all comments for that node. If person A comments and person B replies to it, then both are returned and neither seem to have replies.

**Comment by samchrisinger** [comment]
@Macainian I think neither @abought nor my investigations are showing this... it looks to me that the initial request for a Node's comments is correct. 

That said, replies are definitely broken. A proposed temporary fix is here: https://github.com/CenterForOpenScience/ember-osf/pull/97, and long term we'll need to fix our API implementation.

**Comment by Macainian** [comment]
When I tested this, I had a project that I added a comment to. Then I replied to that comment and then replied to THAT comment and so on. This created a chain of 5 or 6 comments where there was only 1 comment on the upper level and the rest were buried in a reply chain. Then on ember-osf, I looped over that node's comments and instead of showing 1 comment, it showed all of them, implying that it is fetching all comments in the hierarchy.

How did you guys test?

**Comment by abought** [comment]
These initial comment widgets were designed for the dummy app- the emphasis was on verifying basic model operations rather than UI, and the lack of displaying threads is a [known issue](https://github.com/CenterForOpenScience/ember-osf/pull/61).

However, if the API is fetching data for replies in the top-level, that's a bit surprising. I am seeing only the top level comments (not replies) in the response payload for, eg: https://staging-api.osf.io/v2/nodes/m9pv6/comments/?filter%5Btarget%5D=m9pv6

If the `filter[target]` URL parameter is missing in the URL to fetch node comments, you would see all levels of nested reply, and that would be something to look into. We modified the APIv2 behavior a few weeks ago to return the correct URL for the comments relationship, with `filter[target]=item_id` appended.

**Comment by Macainian** [comment]
Any idea on when that filter will be applied to the comments query coming from node in ember-osf? Just curious.

**Comment by abought** [comment]
As far as I can tell, the fix was released, and the necessary URL query param is being applied on staging and on production. 

A sample payload is below, showing the relationship used to ask for node comments. If you aren't seeing a comments relationship link like the below, send me a link to the API endpoint for the (public) project in question, and we'll happily investigate further.

https://api.osf.io/v2/nodes/vhw6d/
```
{
    "data": {
        "relationships": {
            "comments": {
                "links": {
                    "related": {
                        "href": "https://api.osf.io/v2/nodes/vhw6d/comments/?filter[target]=vhw6d",
                        "meta": {}
                    }
                }
            },
...
```

**Comment by Macainian** [comment]
Ok sorry. I misunderstood. I didn't realize it was already patched, otherwise I would have tested it.

**Comment by Macainian** [comment]
So I still haven't had a chance to test this, but I presume it must be working because your frontend widgets on the osf staging site are broken now and only show top level. If you add one while you are on the page then it will display correctly, but if you refresh the page it will all disappear and only show top level.

**Comment by samchrisinger** [comment]
@Macainian that's just how our UI works. Relies are lazily loaded _only_ when the user clicks the expand icon. 
![screen shot 2016-07-12 at 9 24 27 am](https://cloud.githubusercontent.com/assets/2207561/16768514/a5745530-4812-11e6-8bbd-35026ab2b3b3.png)
- - - 
![screen shot 2016-07-12 at 9 24 32 am](https://cloud.githubusercontent.com/assets/2207561/16768515/a57e927a-4812-11e6-85e1-4fba7036a6ae.png)
- - -
Upon refresh: 
![screen shot 2016-07-12 at 9 25 02 am](https://cloud.githubusercontent.com/assets/2207561/16768487/918da602-4812-11e6-8fd4-815c32f47905.png)
 - - -
Upon expand:
![screen shot 2016-07-12 at 9 25 08 am](https://cloud.githubusercontent.com/assets/2207561/16768486/918b22c4-4812-11e6-9b44-14d63146f0c2.png)
- - -

**Comment by Macainian** [comment]
Oh ok. I see. Is the expand button new or did I just forget about? From what I remembered it was just automatically laid out, but perhaps that's just bad memory of mine. I only quickly looked at the page and so I didn't notice the +

**Comment by samchrisinger** [comment]
The expand button should have always been there, but we were having some issues with JS asset builds on staging yesterday (could have caused breakage here).

@Macainian do you think we can mark this issue as resolved?

**Comment by Macainian** [comment]
I haven't been able to test it because I can't get our project working with the current version. However, based on the api, I would guess that it works now.
